openapi: 3.0.0
info:
  title: Synthetix Cache API
  version: 1.0.0
  description: API documentation for the Synthetix Cache API
servers:
  - url: http://localhost:3001
  - url: https://synthetix-cache-api-f7db01015ec1.herokuapp.com
paths:
  allOf:
    - $ref: 'swagger-apy.yaml#/paths'
    - $ref: 'swagger-tvl.yaml#/paths'
    - $ref: 'swagger-core-delegations.yaml#/paths'
    - $ref: 'swagger-core-account-delegations.yaml#/paths'
    - $ref: 'swagger-pool-rewards.yaml#/paths'