CREATE TABLE apy (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ts TIMESTAMP WITH TIME ZONE NOT NULL,
    chain TEXT NOT NULL,
    pool_id INTEGER NOT NULL,
    collateral_type TEXT NOT NULL,
    collateral_value NUMERIC NOT NULL,
    apy_24h NUMERIC NOT NULL,
    apy_7d NUMERIC,
    apy_28d NUMERIC
);